#!/usr/bin/env bash
#
# install_local.sh - Build and install the Raytracer from the current checkout.
#
# This script:
#   1. checks the dependencies required to build the project
#   2. copies the project from this local checkout (no GitHub clone)
#   3. builds the project and its plugins
#   4. creates a "raytracer" command usable from anywhere
#
# System-wide install: the project is placed in /usr/local/share/raytracer
# and the command in /usr/local/bin (privileged operations use sudo). You
# can override this with the RAYTRACER_INSTALL_DIR and RAYTRACER_BIN_DIR
# environment variables.
#
# Usage:
#   ./install_local.sh
#
set -euo pipefail

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------
# Project root to install from: the parent directory of this script.
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="${RAYTRACER_INSTALL_DIR:-/usr/local/share/raytracer}"
BIN_DIR="${RAYTRACER_BIN_DIR:-/usr/local/bin}"
WRAPPER="$BIN_DIR/raytracer"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()  { echo -e "${BLUE}==>${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# Use sudo only when needed (i.e. not already root)
SUDO=""
if [ "$(id -u)" -ne 0 ]; then
    SUDO="sudo"
fi

# --------------------------------------------------------------------------
# 1. Dependency check
# --------------------------------------------------------------------------
info "Checking dependencies..."

MISSING=()
for cmd in make clang++; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        MISSING+=("$cmd")
    fi
done

if [ ${#MISSING[@]} -ne 0 ]; then
    error "Missing dependencies: ${MISSING[*]}"
    echo "  Install them before running again, for example on Debian/Ubuntu:"
    echo "    sudo apt install git make clang libconfig++-dev libsfml-dev"
    echo "  On Fedora:"
    echo "    sudo dnf install git make clang libconfig-devel SFML-devel"
    exit 1
fi
ok "Build tools found (git, make, clang++)"

# Non-blocking check of the runtime libraries
for lib in libconfig sfml-graphics; do
    if command -v pkg-config >/dev/null 2>&1 && ! pkg-config --exists "$lib" 2>/dev/null; then
        warn "Library '$lib' does not seem to be detected by pkg-config."
        warn "If the build fails, install libconfig++-dev and libsfml-dev."
    fi
done

# --------------------------------------------------------------------------
# 2. Copy the project from the current checkout
# --------------------------------------------------------------------------
if [ "$SOURCE_DIR" = "$INSTALL_DIR" ]; then
    error "The current checkout is already the install directory ($INSTALL_DIR)."
    exit 1
fi
info "Copying the project from $SOURCE_DIR into $INSTALL_DIR..."
$SUDO mkdir -p "$INSTALL_DIR"
if command -v rsync >/dev/null 2>&1; then
    # Mirror the checkout, dropping VCS data and build artifacts so the build
    # below starts fresh.
    $SUDO rsync -a --delete \
        --exclude='.git' \
        --exclude='*.o' \
        --exclude='/raytracer' \
        --exclude='plugins/*.so' \
        "$SOURCE_DIR"/ "$INSTALL_DIR"/
else
    $SUDO rm -rf "$INSTALL_DIR"
    $SUDO mkdir -p "$INSTALL_DIR"
    $SUDO cp -a "$SOURCE_DIR"/. "$INSTALL_DIR"/
    $SUDO rm -rf "$INSTALL_DIR/.git"
fi
ok "Project copied"

# --------------------------------------------------------------------------
# 3. Build
# --------------------------------------------------------------------------
info "Building the project (this may take a few minutes)..."
$SUDO make -C "$INSTALL_DIR" re
if [ ! -x "$INSTALL_DIR/raytracer" ]; then
    error "The 'raytracer' binary is missing after the build."
    exit 1
fi
ok "Build complete"

# --------------------------------------------------------------------------
# 4. Create the "raytracer" command
# --------------------------------------------------------------------------
info "Creating the 'raytracer' command in $BIN_DIR..."
$SUDO mkdir -p "$BIN_DIR"

# The binary loads its plugins from "./plugins" (a path relative to the
# current working directory). The wrapper therefore changes into the install
# directory before launching the binary. Since we change directories, we
# first resolve any argument that is an existing file (e.g. the scene) to an
# absolute path so it stays valid.
TMP_WRAPPER="$(mktemp)"
cat > "$TMP_WRAPPER" <<EOF
#!/usr/bin/env bash
# Wrapper generated by installer/install_local.sh - launches the Raytracer.
INSTALL_DIR="$INSTALL_DIR"

# Resolve arguments that point to an existing file/directory to an absolute
# path, so they survive the change of working directory.
args=()
for a in "\$@"; do
    if [ -e "\$a" ]; then
        args+=("\$(realpath "\$a")")
    else
        args+=("\$a")
    fi
done

# Remember where the user launched the command so the binary can write
# relative output files (e.g. the rendered .ppm) back to that directory
# instead of the install directory we are about to switch into.
export RAYTRACER_CWD="\$PWD"

cd "\$INSTALL_DIR" || exit 1
exec "\$INSTALL_DIR/raytracer" "\${args[@]}"
EOF

$SUDO install -m 755 "$TMP_WRAPPER" "$WRAPPER"
rm -f "$TMP_WRAPPER"
ok "Command installed: $WRAPPER"

# --------------------------------------------------------------------------
# 5. PATH check
# --------------------------------------------------------------------------
if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
    warn "The directory $BIN_DIR is not in your PATH."
    echo "  Add this line to your ~/.bashrc or ~/.zshrc:"
    echo "    export PATH=\"$BIN_DIR:\$PATH\""
    echo "  Then reload your terminal (or run 'source ~/.bashrc')."
fi

echo
ok "Installation complete!"
echo "  Launch the project with:"
echo "    raytracer                 # blank scene"
echo "    raytracer <SCENE_FILE>    # with a scene file"
